// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallService.proto

package com.KGAFT.michatmessengerserverproto;

public final class CallServiceOuterClass {
  private CallServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CallDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.KGAFT.michatmessengerserverproto.CallData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 packetId = 1;</code>
     */
    long getPacketId();

    /**
     * <code>int64 userId = 2;</code>
     */
    long getUserId();

    /**
     * <code>int64 roomId = 3;</code>
     */
    long getRoomId();

    /**
     * <code>bytes callData = 4;</code>
     */
    com.google.protobuf.ByteString getCallData();
  }
  /**
   * Protobuf type {@code com.KGAFT.michatmessengerserverproto.CallData}
   */
  public  static final class CallData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.KGAFT.michatmessengerserverproto.CallData)
      CallDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallData.newBuilder() to construct.
    private CallData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallData() {
      callData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CallData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              packetId_ = input.readInt64();
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              roomId_ = input.readInt64();
              break;
            }
            case 34: {

              callData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallData.class, Builder.class);
    }

    public static final int PACKETID_FIELD_NUMBER = 1;
    private long packetId_;
    /**
     * <code>int64 packetId = 1;</code>
     */
    public long getPacketId() {
      return packetId_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int ROOMID_FIELD_NUMBER = 3;
    private long roomId_;
    /**
     * <code>int64 roomId = 3;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int CALLDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString callData_;
    /**
     * <code>bytes callData = 4;</code>
     */
    public com.google.protobuf.ByteString getCallData() {
      return callData_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0L) {
        output.writeInt64(1, packetId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (roomId_ != 0L) {
        output.writeInt64(3, roomId_);
      }
      if (!callData_.isEmpty()) {
        output.writeBytes(4, callData_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packetId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, roomId_);
      }
      if (!callData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, callData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallData)) {
        return super.equals(obj);
      }
      CallData other = (CallData) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getRoomId()
          != other.getRoomId()) return false;
      if (!getCallData()
          .equals(other.getCallData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + CALLDATA_FIELD_NUMBER;
      hash = (53 * hash) + getCallData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.KGAFT.michatmessengerserverproto.CallData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.KGAFT.michatmessengerserverproto.CallData)
        CallDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallData.class, Builder.class);
      }

      // Construct using com.KGAFT.michatmessengerserverproto.CallServiceOuterClass.CallData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        packetId_ = 0L;

        userId_ = 0L;

        roomId_ = 0L;

        callData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor;
      }

      @Override
      public CallData getDefaultInstanceForType() {
        return CallData.getDefaultInstance();
      }

      @Override
      public CallData build() {
        CallData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CallData buildPartial() {
        CallData result = new CallData(this);
        result.packetId_ = packetId_;
        result.userId_ = userId_;
        result.roomId_ = roomId_;
        result.callData_ = callData_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallData) {
          return mergeFrom((CallData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallData other) {
        if (other == CallData.getDefaultInstance()) return this;
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getCallData() != com.google.protobuf.ByteString.EMPTY) {
          setCallData(other.getCallData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long packetId_ ;
      /**
       * <code>int64 packetId = 1;</code>
       */
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>int64 packetId = 1;</code>
       */
      public Builder setPacketId(long value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packetId = 1;</code>
       */
      public Builder clearPacketId() {
        
        packetId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long roomId_ ;
      /**
       * <code>int64 roomId = 3;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>int64 roomId = 3;</code>
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 roomId = 3;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString callData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes callData = 4;</code>
       */
      public com.google.protobuf.ByteString getCallData() {
        return callData_;
      }
      /**
       * <code>bytes callData = 4;</code>
       */
      public Builder setCallData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        callData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes callData = 4;</code>
       */
      public Builder clearCallData() {
        
        callData_ = getDefaultInstance().getCallData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.KGAFT.michatmessengerserverproto.CallData)
    }

    // @@protoc_insertion_point(class_scope:com.KGAFT.michatmessengerserverproto.CallData)
    private static final CallData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallData();
    }

    public static CallData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallData>
        PARSER = new com.google.protobuf.AbstractParser<CallData>() {
      @Override
      public CallData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallData> getParserForType() {
      return PARSER;
    }

    @Override
    public CallData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReceiveDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.KGAFT.michatmessengerserverproto.ReceiveData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 roomId = 1;</code>
     */
    long getRoomId();

    /**
     * <code>int64 userId = 2;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code com.KGAFT.michatmessengerserverproto.ReceiveData}
   */
  public  static final class ReceiveData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.KGAFT.michatmessengerserverproto.ReceiveData)
      ReceiveDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReceiveData.newBuilder() to construct.
    private ReceiveData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReceiveData() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReceiveData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReceiveData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              roomId_ = input.readInt64();
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReceiveData.class, Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private long roomId_;
    /**
     * <code>int64 roomId = 1;</code>
     */
    public long getRoomId() {
      return roomId_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomId_ != 0L) {
        output.writeInt64(1, roomId_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, roomId_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReceiveData)) {
        return super.equals(obj);
      }
      ReceiveData other = (ReceiveData) obj;

      if (getRoomId()
          != other.getRoomId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRoomId());
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReceiveData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReceiveData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReceiveData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReceiveData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReceiveData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReceiveData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReceiveData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReceiveData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReceiveData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReceiveData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReceiveData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReceiveData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReceiveData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.KGAFT.michatmessengerserverproto.ReceiveData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.KGAFT.michatmessengerserverproto.ReceiveData)
        ReceiveDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReceiveData.class, Builder.class);
      }

      // Construct using com.KGAFT.michatmessengerserverproto.CallServiceOuterClass.ReceiveData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        roomId_ = 0L;

        userId_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor;
      }

      @Override
      public ReceiveData getDefaultInstanceForType() {
        return ReceiveData.getDefaultInstance();
      }

      @Override
      public ReceiveData build() {
        ReceiveData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ReceiveData buildPartial() {
        ReceiveData result = new ReceiveData(this);
        result.roomId_ = roomId_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReceiveData) {
          return mergeFrom((ReceiveData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReceiveData other) {
        if (other == ReceiveData.getDefaultInstance()) return this;
        if (other.getRoomId() != 0L) {
          setRoomId(other.getRoomId());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReceiveData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReceiveData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long roomId_ ;
      /**
       * <code>int64 roomId = 1;</code>
       */
      public long getRoomId() {
        return roomId_;
      }
      /**
       * <code>int64 roomId = 1;</code>
       */
      public Builder setRoomId(long value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 roomId = 1;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.KGAFT.michatmessengerserverproto.ReceiveData)
    }

    // @@protoc_insertion_point(class_scope:com.KGAFT.michatmessengerserverproto.ReceiveData)
    private static final ReceiveData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReceiveData();
    }

    public static ReceiveData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReceiveData>
        PARSER = new com.google.protobuf.AbstractParser<ReceiveData>() {
      @Override
      public ReceiveData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReceiveData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReceiveData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReceiveData> getParserForType() {
      return PARSER;
    }

    @Override
    public ReceiveData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface nullResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.KGAFT.michatmessengerserverproto.nullResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.KGAFT.michatmessengerserverproto.nullResponse}
   */
  public  static final class nullResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.KGAFT.michatmessengerserverproto.nullResponse)
      nullResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use nullResponse.newBuilder() to construct.
    private nullResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private nullResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new nullResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private nullResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nullResponse.class, Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nullResponse)) {
        return super.equals(obj);
      }
      nullResponse other = (nullResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nullResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nullResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nullResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nullResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nullResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nullResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nullResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nullResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nullResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nullResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nullResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nullResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nullResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.KGAFT.michatmessengerserverproto.nullResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.KGAFT.michatmessengerserverproto.nullResponse)
        nullResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nullResponse.class, Builder.class);
      }

      // Construct using com.KGAFT.michatmessengerserverproto.CallServiceOuterClass.nullResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor;
      }

      @Override
      public nullResponse getDefaultInstanceForType() {
        return nullResponse.getDefaultInstance();
      }

      @Override
      public nullResponse build() {
        nullResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public nullResponse buildPartial() {
        nullResponse result = new nullResponse(this);
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nullResponse) {
          return mergeFrom((nullResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nullResponse other) {
        if (other == nullResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nullResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nullResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.KGAFT.michatmessengerserverproto.nullResponse)
    }

    // @@protoc_insertion_point(class_scope:com.KGAFT.michatmessengerserverproto.nullResponse)
    private static final nullResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nullResponse();
    }

    public static nullResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<nullResponse>
        PARSER = new com.google.protobuf.AbstractParser<nullResponse>() {
      @Override
      public nullResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new nullResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<nullResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<nullResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public nullResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CallDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.KGAFT.michatmessengerserverproto.CallDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 packetId = 1;</code>
     */
    long getPacketId();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int64 userId = 3;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code com.KGAFT.michatmessengerserverproto.CallDataResponse}
   */
  public  static final class CallDataResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.KGAFT.michatmessengerserverproto.CallDataResponse)
      CallDataResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CallDataResponse.newBuilder() to construct.
    private CallDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CallDataResponse() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CallDataResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CallDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              packetId_ = input.readInt64();
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
            case 24: {

              userId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CallDataResponse.class, Builder.class);
    }

    public static final int PACKETID_FIELD_NUMBER = 1;
    private long packetId_;
    /**
     * <code>int64 packetId = 1;</code>
     */
    public long getPacketId() {
      return packetId_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private long userId_;
    /**
     * <code>int64 userId = 3;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0L) {
        output.writeInt64(1, packetId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      if (userId_ != 0L) {
        output.writeInt64(3, userId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packetId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CallDataResponse)) {
        return super.equals(obj);
      }
      CallDataResponse other = (CallDataResponse) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CallDataResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallDataResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CallDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CallDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CallDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CallDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CallDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CallDataResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.KGAFT.michatmessengerserverproto.CallDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.KGAFT.michatmessengerserverproto.CallDataResponse)
        CallDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CallDataResponse.class, Builder.class);
      }

      // Construct using com.KGAFT.michatmessengerserverproto.CallServiceOuterClass.CallDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        packetId_ = 0L;

        data_ = com.google.protobuf.ByteString.EMPTY;

        userId_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CallServiceOuterClass.internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor;
      }

      @Override
      public CallDataResponse getDefaultInstanceForType() {
        return CallDataResponse.getDefaultInstance();
      }

      @Override
      public CallDataResponse build() {
        CallDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CallDataResponse buildPartial() {
        CallDataResponse result = new CallDataResponse(this);
        result.packetId_ = packetId_;
        result.data_ = data_;
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CallDataResponse) {
          return mergeFrom((CallDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CallDataResponse other) {
        if (other == CallDataResponse.getDefaultInstance()) return this;
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CallDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CallDataResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long packetId_ ;
      /**
       * <code>int64 packetId = 1;</code>
       */
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>int64 packetId = 1;</code>
       */
      public Builder setPacketId(long value) {
        
        packetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packetId = 1;</code>
       */
      public Builder clearPacketId() {
        
        packetId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 3;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 3;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 3;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.KGAFT.michatmessengerserverproto.CallDataResponse)
    }

    // @@protoc_insertion_point(class_scope:com.KGAFT.michatmessengerserverproto.CallDataResponse)
    private static final CallDataResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CallDataResponse();
    }

    public static CallDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CallDataResponse>
        PARSER = new com.google.protobuf.AbstractParser<CallDataResponse>() {
      @Override
      public CallDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CallDataResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CallDataResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CallDataResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public CallDataResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_KGAFT_michatmessengerserverproto_CallData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021CallService.proto\022$com.KGAFT.michatmes" +
      "sengerserverproto\"N\n\010CallData\022\020\n\010packetI" +
      "d\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\022\016\n\006roomId\030\003 \001(\003\022" +
      "\020\n\010callData\030\004 \001(\014\"-\n\013ReceiveData\022\016\n\006room" +
      "Id\030\001 \001(\003\022\016\n\006userId\030\002 \001(\003\"\016\n\014nullResponse" +
      "\"B\n\020CallDataResponse\022\020\n\010packetId\030\001 \001(\003\022\014" +
      "\n\004data\030\002 \001(\014\022\016\n\006userId\030\003 \001(\0032\201\002\n\013CallSer" +
      "vice\022r\n\014sendCallData\022..com.KGAFT.michatm" +
      "essengerserverproto.CallData\0322.com.KGAFT" +
      ".michatmessengerserverproto.nullResponse" +
      "\022~\n\017receiveCallData\0221.com.KGAFT.michatme" +
      "ssengerserverproto.ReceiveData\0326.com.KGA" +
      "FT.michatmessengerserverproto.CallDataRe" +
      "sponse0\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_KGAFT_michatmessengerserverproto_CallData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_KGAFT_michatmessengerserverproto_CallData_descriptor,
        new String[] { "PacketId", "UserId", "RoomId", "CallData", });
    internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_KGAFT_michatmessengerserverproto_ReceiveData_descriptor,
        new String[] { "RoomId", "UserId", });
    internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_KGAFT_michatmessengerserverproto_nullResponse_descriptor,
        new String[] { });
    internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_KGAFT_michatmessengerserverproto_CallDataResponse_descriptor,
        new String[] { "PacketId", "Data", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
